#!/bin/sh
set -e

# Install from nodesource
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt install -y nodejs

# Installer
mkdir -p /opt/healthcheck
(cd /opt/healthcheck && npm install express)

# Create startup item
sed -i "$ i\screen -dmS healthcheck-runner node /opt/healthcheck/init.js" /etc/userd.local